SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DECLARE @now datetime2 = SYSUTCDATETIME();
DECLARE @items TABLE (
    [Kind] tinyint NOT NULL,
    [Name] nvarchar(256) NOT NULL,
    [SortOrder] int NOT NULL
);

INSERT INTO @items ([Kind], [Name], [SortOrder]) VALUES
    (0, N'Academia', 0),
    (0, N'Addiction', 1),
    (0, N'Adolescent health', 2),
    (0, N'Agribusiness', 3),
    (0, N'Alternative Economy', 4),
    (0, N'Analytical Chemistry', 5),
    (0, N'Anthropology', 6),
    (0, N'Arabic and Near Eastern Languages', 7),
    (0, N'Arabic translation of health research tools/methods', 8),
    (0, N'Archeology', 9),
    (0, N'Architecture', 10),
    (0, N'Art History', 11),
    (0, N'Artificial intelligence', 12),
    (0, N'Auditing', 13),
    (0, N'Banking', 14),
    (0, N'Behavioral Change', 15),
    (0, N'Biology', 16),
    (0, N'Biomechanics', 17),
    (0, N'Biomedical Engineering', 18),
    (0, N'Budgeting', 19),
    (0, N'Bullying', 20),
    (0, N'Business', 21),
    (0, N'Business Ethics/Sustainability/Corporate Social Responsibility', 22),
    (0, N'Capacity-building project', 23),
    (0, N'Cardiovascular Health', 24),
    (0, N'Caregiver Support', 25),
    (0, N'Chemical engineering', 26),
    (0, N'chemistry', 27),
    (0, N'Chronic Diseases', 28),
    (0, N'Civic Engagement & Community Support Projects', 29),
    (0, N'Climate Change Research', 30),
    (0, N'Cognition', 31),
    (0, N'Cognitive Function and Rehabilitation', 32),
    (0, N'Communicable diseases', 33),
    (0, N'Communications and networking', 34),
    (0, N'Community organizations, inc. CHVs', 35),
    (0, N'Community-based health promotion and healthcare services', 36),
    (0, N'Computational Modeling', 37),
    (0, N'Computer hardware systems', 38),
    (0, N'Computer Sciences', 39),
    (0, N'Conflict', 40),
    (0, N'Construction engineering and management', 41),
    (0, N'Control systems', 42),
    (0, N'Corporate Finance/Mergers & Acquisitions/IPOs', 43),
    (0, N'Corporate Governance/CEO Succession/Leadership', 44),
    (0, N'Corporate Law', 45),
    (0, N'Depression', 46),
    (0, N'Design and Development', 47),
    (0, N'Design, materials, and manufacturing', 48),
    (0, N'Digital Business', 49),
    (0, N'Digital Cartography', 50),
    (0, N'Digitalization', 51),
    (0, N'Ecology', 52),
    (0, N'Economics', 53),
    (0, N'Education', 54),
    (0, N'electrical engineering', 55),
    (0, N'Energy systems', 56),
    (0, N'Engineering management', 57),
    (0, N'English', 58),
    (0, N'Entrepreneurship', 59),
    (0, N'Environmental engineering', 60),
    (0, N'Environmental Sciences', 61),
    (0, N'Essential medicines, medical products, vaccines and technologies', 62),
    (0, N'Experimental Physics', 63),
    (0, N'Experimental Physiology', 64),
    (0, N'Family Business', 65),
    (0, N'Film Studies', 66),
    (0, N'Financial Reporting', 67),
    (0, N'Financing', 68),
    (0, N'Food sciences', 69),
    (0, N'Food security', 70),
    (0, N'Gender', 71),
    (0, N'gender studies', 72),
    (0, N'Genetics', 73),
    (0, N'Geography', 74),
    (0, N'Geology', 75),
    (0, N'Geotechnical engineering', 76),
    (0, N'Global health (inc. refugees/displaced populations)', 77),
    (0, N'Graphic design', 78),
    (0, N'Health behaviors', 79),
    (0, N'Health information systems, inc. eHealth, digital health', 80),
    (0, N'Health outcomes', 81),
    (0, N'Health systems/health policy', 82),
    (0, N'Health workforce', 83),
    (0, N'History', 84),
    (0, N'Household production of health', 85),
    (0, N'Human factors and ergonomics', 86),
    (0, N'Human Resources', 87),
    (0, N'Implementation research', 88),
    (0, N'Information Systems/Data Analytics', 89),
    (0, N'Information, learning and accountability', 90),
    (0, N'Injuries', 91),
    (0, N'Innovative technologies in water and agriculture', 92),
    (0, N'Inorganic Chemistry', 93),
    (0, N'Institution-building project', 94),
    (0, N'International Business', 95),
    (0, N'International health', 96),
    (0, N'Investments', 97),
    (0, N'Landscape for culture and socio-ecological health', 98),
    (0, N'Leadership/governance', 99),
    (0, N'Machine learning', 100),
    (0, N'Marketing/Consumer Behavior/Social Media', 101),
    (0, N'Mathematics and Applied Mathematics', 102),
    (0, N'Mechatronics', 103),
    (0, N'Media Studies', 104),
    (0, N'Mental health', 105),
    (0, N'Molecular and Cell Biology', 106),
    (0, N'Nanoengineering and biosensors', 107),
    (0, N'Neural engineering and neuroscience', 108),
    (0, N'Non-communicable diseases (NCDs)', 109),
    (0, N'Nursing Workforce', 110),
    (0, N'Nutrition and health', 111),
    (0, N'Obesity in Adolescents', 112),
    (0, N'Occupational health', 113),
    (0, N'Older adults', 114),
    (0, N'Operations', 115),
    (0, N'Operations research', 116),
    (0, N'Operations Research/Supply Chain Management/Logistics', 117),
    (0, N'Organic Chemistry', 118),
    (0, N'Organization', 119),
    (0, N'Organizational Behavior', 120),
    (0, N'Pain in Children', 121),
    (0, N'Pavement materials', 122),
    (0, N'Petroleum engineering', 123),
    (0, N'Philosophy', 124),
    (0, N'Physical Chemistry', 125),
    (0, N'Physical environment', 126),
    (0, N'Physiological modeling', 127),
    (0, N'Plant and animal sciences', 128),
    (0, N'Political Studies', 129),
    (0, N'Power and energy systems', 130),
    (0, N'Psychological Wellbeing', 131),
    (0, N'Psychology', 132),
    (0, N'Public Administration', 133),
    (0, N'Public Policy & Governance', 134),
    (0, N'Qualitative Research Methods', 135),
    (0, N'Refugee Education', 136),
    (0, N'Refugee Health', 137),
    (0, N'Religious studies', 138),
    (0, N'Remote Sensing', 139),
    (0, N'Research ethics', 140),
    (0, N'Risk and protective factors', 141),
    (0, N'Rural and community development', 142),
    (0, N'School or university-based programs', 143),
    (0, N'Seismology', 144),
    (0, N'Self-Care', 145),
    (0, N'Self-Esteem', 146),
    (0, N'Service delivery', 147),
    (0, N'Sexual Harassment', 148),
    (0, N'Sexuality', 149),
    (0, N'Signal Processing', 150),
    (0, N'Social determinants of health', 151),
    (0, N'Societal partnerships', 152),
    (0, N'Sociology', 153),
    (0, N'Software systems', 154),
    (0, N'Statistical Modeling/Probability/Forecasting', 155),
    (0, N'Strategy', 156),
    (0, N'Structural engineering', 157),
    (0, N'Studio Art', 158),
    (0, N'Symptom Science', 159),
    (0, N'Theoretical Physics', 160),
    (0, N'Thermal and fluids engineering', 161),
    (0, N'Tissue engineering and drug delivery', 162),
    (0, N'Transportation', 163),
    (0, N'Urban Anthropology', 164),
    (0, N'Urban design', 165),
    (0, N'Urban History', 166),
    (0, N'Urban planning and policy', 167),
    (0, N'Urban Studies', 168),
    (0, N'Water and food security', 169),
    (0, N'Water resources', 170),
    (0, N'web design', 171),
    (0, N'WebGIS', 172),
    (0, N'website development', 173),
    (0, N'women''s economic empowerment', 174),
    (1, N'3D Modelling', 0),
    (1, N'Achiral Research', 1),
    (1, N'Archeological Field Work', 2),
    (1, N'Cataloging', 3),
    (1, N'Coding', 4),
    (1, N'Conducting a Case Study', 5),
    (1, N'Conducting a Survey', 6),
    (1, N'Data analysis - geospatial', 7),
    (1, N'Data analysis - qualitative', 8),
    (1, N'Data analysis - quantitative', 9),
    (1, N'Data Collection', 10),
    (1, N'Data Entry', 11),
    (1, N'Data management (includes data documentation)', 12),
    (1, N'Data Visualization', 13),
    (1, N'Device development', 14),
    (1, N'digital communication', 15),
    (1, N'Experimental/Wet Lab work', 16),
    (1, N'Field work/Data Collection', 17),
    (1, N'Image Search', 18),
    (1, N'Instrumentation', 19),
    (1, N'Interview Transcriptions', 20),
    (1, N'Literature Search', 21),
    (1, N'Logo Design', 22),
    (1, N'Manuscript Writing', 23),
    (1, N'Meta-analysis', 24),
    (1, N'Online Research on Databases', 25),
    (1, N'Participatory-Action research', 26),
    (1, N'Photography', 27),
    (1, N'Poster Preparation', 28),
    (1, N'Programming', 29),
    (1, N'Project Management', 30),
    (1, N'Proposal Writing', 31),
    (1, N'Reports Writing', 32),
    (1, N'Research dissemination - creating presentations', 33),
    (1, N'Research Dissemination (Manuscript Writing; Conference Presentation)', 34),
    (1, N'Researching and evaluating software', 35),
    (1, N'Researching methodologies', 36),
    (1, N'Researching theories and conceptual frameworks', 37),
    (1, N'Simulation', 38),
    (1, N'Statistical analysis', 39),
    (1, N'Systematic review', 40),
    (1, N'Theater', 41),
    (1, N'Theoretical Work', 42),
    (1, N'Transcription', 43),
    (1, N'Translating', 44),
    (1, N'web design', 45),
    (1, N'website development', 46),
    (1, N'Writing a Literature Review', 47),
    (1, N'Writing a Research Proposal', 48)
;

INSERT INTO [ValueListItems] ([Id], [Kind], [Name], [SortOrder], [IsActive], [CreatedAt], [UpdatedAt])
SELECT NEWID(), i.[Kind], i.[Name], i.[SortOrder], 1, @now, @now
FROM @items AS i
WHERE NOT EXISTS (
    SELECT 1
    FROM [ValueListItems] AS v
    WHERE v.[Kind] = i.[Kind]
      AND v.[Name] = i.[Name]
);

COMMIT;
GO
