trigger:
- DevTest

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '22.16.0'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'ci'
    workingDir: 'FEA.URVP.Frontend'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: 'FEA.URVP.Frontend'
