namespace FEA.URVP.Domain.Catalog;

/// <summary>
/// Allowed research-area labels for project posting (max 6 per project).
/// </summary>
public static class ResearchAreaCatalog
{
    public const int MaxSelections = 6;

    public static readonly IReadOnlySet<string> Allowed = new HashSet<string>(StringComparer.Ordinal)
    {
        "Academia",
        "Addiction",
        "Adolescent health",
        "Agribusiness",
        "Alternative Economy",
        "Analytical Chemistry",
        "Anthropology",
        "Arabic and Near Eastern Languages",
        "Arabic translation of health research tools/methods",
        "Archeology",
        "Architecture",
        "Art History",
        "Artificial intelligence",
        "Auditing",
        "Banking",
        "Behavioral Change",
        "Biology",
        "Biomechanics",
        "Biomedical Engineering",
        "Budgeting",
        "Bullying",
        "Business",
        "Business Ethics/Sustainability/Corporate Social Responsibility",
        "Capacity-building project",
        "Cardiovascular Health",
        "Caregiver Support",
        "Chemical engineering",
        "Chronic Diseases",
        "Civic Engagement & Community Support Projects",
        "Climate Change Research",
        "Cognition",
        "Cognitive Function and Rehabilitation",
        "Communicable diseases",
        "Communications and networking",
        "Community organizations, inc. CHVs",
        "Community-based health promotion and healthcare services",
        "Computational Modeling",
        "Computer Sciences",
        "Computer hardware systems",
        "Conflict",
        "Construction engineering and management",
        "Control systems",
        "Corporate Finance/Mergers & Acquisitions/IPOs",
        "Corporate Governance/CEO Succession/Leadership",
        "Corporate Law",
        "Depression",
        "Design and Development",
        "Design, materials, and manufacturing",
        "Digital Business",
        "Digital Cartography",
        "Digitalization",
        "Ecology",
        "Economics",
        "Education",
        "Energy systems",
        "Engineering management",
        "English",
        "Entrepreneurship",
        "Environmental Sciences",
        "Environmental engineering",
        "Essential medicines, medical products, vaccines and technologies",
        "Experimental Physics",
        "Experimental Physiology",
        "Family Business",
        "Film Studies",
        "Financial Reporting",
        "Financing",
        "Food sciences",
        "Food security",
        "Gender",
        "Genetics",
        "Geography",
        "Geology",
        "Geotechnical engineering",
        "Global health (inc. refugees/displaced populations)",
        "Graphic design",
        "Health behaviors",
        "Health information systems, inc. eHealth, digital health",
        "Health outcomes",
        "Health systems/health policy",
        "Health workforce",
        "History",
        "Household production of health",
        "Human Resources",
        "Human factors and ergonomics",
        "Implementation research",
        "Information Systems/Data Analytics",
        "Information, learning and accountability",
        "Injuries",
        "Innovative technologies in water and agriculture",
        "Inorganic Chemistry",
        "Institution-building project",
        "International Business",
        "International health",
        "Investments",
        "Landscape for culture and socio-ecological health",
        "Leadership/governance",
        "Machine learning",
        "Marketing/Consumer Behavior/Social Media",
        "Mathematics and Applied Mathematics",
        "Mechatronics",
        "Media Studies",
        "Mental health",
        "Molecular and Cell Biology",
        "Nanoengineering and biosensors",
        "Neural engineering and neuroscience",
        "Non-communicable diseases (NCDs)",
        "Nursing Workforce",
        "Nutrition and health",
        "Obesity in Adolescents",
        "Occupational health",
        "Older adults",
        "Operations",
        "Operations Research/Supply Chain Management/Logistics",
        "Operations research",
        "Organic Chemistry",
        "Organization",
        "Organizational Behavior",
        "Pain in Children",
        "Pavement materials",
        "Petroleum engineering",
        "Philosophy",
        "Physical Chemistry",
        "Physical environment",
        "Physiological modeling",
        "Plant and animal sciences",
        "Political Studies",
        "Power and energy systems",
        "Psychological Wellbeing",
        "Psychology",
        "Public Administration",
        "Public Policy & Governance",
        "Qualitative Research Methods",
        "Refugee Education",
        "Refugee Health",
        "Religious studies",
        "Remote Sensing",
        "Research ethics",
        "Risk and protective factors",
        "Rural and community development",
        "School or university-based programs",
        "Seismology",
        "Self-Care",
        "Self-Esteem",
        "Service delivery",
        "Sexual Harassment",
        "Sexuality",
        "Signal Processing",
        "Social determinants of health",
        "Societal partnerships",
        "Sociology",
        "Software systems",
        "Statistical Modeling/Probability/Forecasting",
        "Strategy",
        "Structural engineering",
        "Studio Art",
        "Symptom Science",
        "Theoretical Physics",
        "Thermal and fluids engineering",
        "Tissue engineering and drug delivery",
        "Transportation",
        "Urban Anthropology",
        "Urban History",
        "Urban Studies",
        "Urban design",
        "Urban planning and policy",
        "Water and food security",
        "Water resources",
        "WebGIS",
        "chemistry",
        "electrical engineering",
        "gender studies",
        "web design",
        "website development",
        "women's economic empowerment",
    };
}
